try{ 
    console.log(varia)
} catch{
    console.log('algo deu errado')
}